"""Initial migration

Revision ID: 554ccc0840fe
Revises: 
Create Date: 2025-02-28 11:26:28.182117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554ccc0840fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('movie_title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('movie_genres', sa.VARCHAR(length=100), nullable=False),
    sa.Column('movie_ratings', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('user_gender', sa.INTEGER(), nullable=False),
    sa.Column('user_occupation_label', sa.INTEGER(), nullable=False),
    sa.Column('raw_user_age', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
